# Generated by Django 4.2.6 on 2024-01-06 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.IntegerField()),
                ('Title', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
                ('Course_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moshaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoshaverID', models.IntegerField()),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('Madrak', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.IntegerField()),
                ('PersonID', models.IntegerField()),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('School_Name', models.CharField(max_length=50)),
                ('Study', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('GPA', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Courses_has_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.courses')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.moshaver')),
            ],
        ),
        migrations.CreateModel(
            name='Course_has_Moshaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.courses')),
                ('MoshaverID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.moshaver')),
            ],
        ),
    ]
