# Generated by Django 4.2.6 on 2024-01-07 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_has_user',
            name='PersonID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
