# Generated by Django 4.2.6 on 2024-01-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_courses_has_user_personid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses_has_user',
            name='CourseID',
        ),
        migrations.RemoveField(
            model_name='courses_has_user',
            name='PersonID',
        ),
        migrations.DeleteModel(
            name='Course_has_Moshaver',
        ),
        migrations.DeleteModel(
            name='Courses_has_User',
        ),
    ]
