# Generated by Django 5.0.1 on 2024-01-26 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_courses_has_user_courseid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='Moshaver',
            field=models.CharField(default='نامشخص', max_length=20),
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default='نامشخص', max_length=200),
        ),
        migrations.CreateModel(
            name='Course_has_Moshaver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.courses')),
                ('MoshaverID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.moshaver')),
            ],
        ),
        migrations.CreateModel(
            name='Courses_has_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.courses')),
                ('PersonID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
